[package]
name = "indextree-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
thiserror = "1.0.61"
either = "1.13.0"
syn = { version = "2.0.71", features = ["extra-traits", "full", "visit"] }
